sudo: false
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
  - "pypy"
  - "pypy3"
env:
  - TYPING_VERSION="<3.5.3"
  - TYPING_VERSION=">=3.5.3"
matrix:
  allow_failures:
    - python: "3.5-dev"
    - python: "nightly"

install:
  - pip install pytest "typing$TYPING_VERSION"
script: py.test -vv
