sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy"
  - "pypy3.3-5.2-alpha1"
env:
  - TYPING_VERSION="<3.5.3"
  - TYPING_VERSION=">=3.5.3"
matrix:
  allow_failures:
    - python: "nightly"

install:
  - pip install pytest "typing$TYPING_VERSION" "pytest-cov>=2.5.1"
script: py.test -vv --cov=injector --cov-branch --cov-report html --cov-report term
